/**
 * PMCopilot - Export Utilities
 * Export analysis results in various formats (PDF, Markdown, JSON, CSV)
 */

import { ComprehensiveAnalysisResult } from '@/types/analysis'

/**
 * Export analysis as Markdown
 */
export function exportAsMarkdown(analysis: ComprehensiveAnalysisResult): string {
  let md = `# Analysis Report\n\n`
  md += `**Generated:** ${new Date(analysis.created_at).toLocaleString()}\n`
  md += `**Analysis ID:** ${analysis.analysis_id}\n`
  md += `**Processing Time:** ${analysis.processing_time_ms}ms\n`
  md += `**Model:** ${analysis.model_used}\n\n`

  // Executive Summary
  md += `## Executive Summary\n\n`
  md += `${analysis.executive_summary}\n\n`

  // Key Findings
  md += `## Key Findings\n\n`
  analysis.key_findings.forEach((finding, i) => {
    md += `${i + 1}. ${finding}\n`
  })
  md += `\n`

  // Immediate Actions
  md += `## Immediate Actions\n\n`
  analysis.immediate_actions.forEach((action, i) => {
    md += `- ${action}\n`
  })
  md += `\n`

  // Problems
  md += `## Problems Identified (${analysis.problems.length})\n\n`
  analysis.problems.forEach((problem, i) => {
    md += `### ${i + 1}. ${problem.title}\n\n`
    md += `**Severity:** ${problem.severity_score}/10 | **Frequency:** ${problem.frequency_score}/10\n\n`
    md += `${problem.description}\n\n`
    if (problem.evidence && problem.evidence.length > 0) {
      md += `**Evidence:**\n`
      problem.evidence.forEach(ev => {
        md += `> "${ev}"\n\n`
      })
    }
    md += `---\n\n`
  })

  // Features
  md += `## Feature Suggestions (${analysis.features.length})\n\n`
  analysis.features.forEach((feature, i) => {
    md += `### ${i + 1}. ${feature.name} [${feature.priority} Priority]\n\n`
    md += `**Complexity:** ${feature.complexity || 'Not specified'}\n\n`
    md += `**Reason:** ${feature.reason}\n\n`
    if (feature.estimated_impact) {
      md += `**Expected Impact:** ${feature.estimated_impact}\n\n`
    }
    md += `---\n\n`
  })

  // PRD
  md += `## Product Requirements Document\n\n`
  md += `### Problem Statement\n\n${analysis.prd.problem_statement}\n\n`
  md += `### Proposed Solution\n\n${analysis.prd.solution_overview}\n\n`

  md += `### Goals\n\n`
  analysis.prd.goals?.forEach(goal => {
    md += `- ${goal}\n`
  })
  md += `\n`

  md += `### Non-Goals\n\n`
  analysis.prd.non_goals?.forEach(nonGoal => {
    md += `- ${nonGoal}\n`
  })
  md += `\n`

  // User Stories
  md += `### User Stories\n\n`
  analysis.prd.user_stories?.forEach((story, i) => {
    md += `${i + 1}. **As a** ${story.persona}, **I want to** ${story.action}, **so that** ${story.benefit}\n`
  })
  md += `\n`

  // Tasks
  md += `## Development Tasks (${analysis.tasks.length})\n\n`
  const tasksByType = analysis.tasks.reduce((acc, task) => {
    if (!acc[task.type]) acc[task.type] = []
    acc[task.type].push(task)
    return acc
  }, {} as Record<string, typeof analysis.tasks>)

  Object.entries(tasksByType).forEach(([type, tasks]) => {
    md += `### ${type.charAt(0).toUpperCase() + type.slice(1)} Tasks\n\n`
    tasks.forEach(task => {
      md += `- **${task.title}** [${task.priority}, ${task.story_points || '?'} SP]\n`
      md += `  ${task.description}\n`
    })
    md += `\n`
  })

  // Impact
  md += `## Impact Estimation\n\n`
  md += `- **User Impact:** ${analysis.impact.user_impact_score}/10 - ${analysis.impact.user_impact}\n`
  md += `- **Business Impact:** ${analysis.impact.business_impact_score}/10 - ${analysis.impact.business_impact}\n`
  md += `- **Confidence:** ${Math.round(analysis.impact.confidence_score * 100)}%\n`
  if (analysis.impact.time_to_value) {
    md += `- **Time to Value:** ${analysis.impact.time_to_value}\n`
  }
  md += `\n`

  // Methodology
  md += `## Methodology\n\n`
  md += `${analysis.explainability.methodology}\n\n`
  md += `**Data Quality Score:** ${Math.round(analysis.explainability.data_quality_score * 100)}%\n\n`
  md += `**Confidence Factors:**\n`
  analysis.explainability.confidence_factors.forEach(factor => {
    md += `- ${factor}\n`
  })
  md += `\n`

  md += `**Limitations:**\n`
  analysis.explainability.limitations.forEach(limitation => {
    md += `- ${limitation}\n`
  })
  md += `\n`

  md += `---\n`
  md += `*Generated by PMCopilot - AI-Powered Product Management*\n`

  return md
}

/**
 * Export analysis as JSON
 */
export function exportAsJSON(analysis: ComprehensiveAnalysisResult): string {
  return JSON.stringify(analysis, null, 2)
}

/**
 * Export problems as CSV
 */
export function exportProblemsAsCSV(analysis: ComprehensiveAnalysisResult): string {
  let csv = 'ID,Title,Description,Severity,Frequency,Category,Evidence Count\n'

  analysis.problems.forEach(problem => {
    const row = [
      problem.id,
      `"${problem.title.replace(/"/g, '""')}"`,
      `"${problem.description.replace(/"/g, '""')}"`,
      problem.severity_score,
      problem.frequency_score,
      problem.category || 'N/A',
      problem.evidence?.length || 0
    ]
    csv += row.join(',') + '\n'
  })

  return csv
}

/**
 * Export features as CSV
 */
export function exportFeaturesAsCSV(analysis: ComprehensiveAnalysisResult): string {
  let csv = 'ID,Name,Priority,Complexity,Reason,Linked Problems\n'

  analysis.features.forEach(feature => {
    const row = [
      feature.id,
      `"${feature.name.replace(/"/g, '""')}"`,
      feature.priority,
      feature.complexity || 'N/A',
      `"${feature.reason.replace(/"/g, '""')}"`,
      feature.linked_problems?.length || 0
    ]
    csv += row.join(',') + '\n'
  })

  return csv
}

/**
 * Export tasks as CSV (Linear/Jira compatible)
 */
export function exportTasksAsCSV(analysis: ComprehensiveAnalysisResult): string {
  let csv = 'ID,Title,Type,Priority,Story Points,Status,Description\n'

  analysis.tasks.forEach(task => {
    const row = [
      task.id,
      `"${task.title.replace(/"/g, '""')}"`,
      task.type,
      task.priority,
      task.story_points || '',
      'To Do',
      `"${task.description.replace(/"/g, '""')}"`
    ]
    csv += row.join(',') + '\n'
  })

  return csv
}

/**
 * Download file in browser
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export utility with all formats
 */
export const exportAnalysis = {
  markdown: (analysis: ComprehensiveAnalysisResult, filename?: string) => {
    const content = exportAsMarkdown(analysis)
    downloadFile(
      content,
      filename || `analysis-${analysis.analysis_id}.md`,
      'text/markdown'
    )
  },

  json: (analysis: ComprehensiveAnalysisResult, filename?: string) => {
    const content = exportAsJSON(analysis)
    downloadFile(
      content,
      filename || `analysis-${analysis.analysis_id}.json`,
      'application/json'
    )
  },

  problemsCSV: (analysis: ComprehensiveAnalysisResult, filename?: string) => {
    const content = exportProblemsAsCSV(analysis)
    downloadFile(
      content,
      filename || `problems-${analysis.analysis_id}.csv`,
      'text/csv'
    )
  },

  featuresCSV: (analysis: ComprehensiveAnalysisResult, filename?: string) => {
    const content = exportFeaturesAsCSV(analysis)
    downloadFile(
      content,
      filename || `features-${analysis.analysis_id}.csv`,
      'text/csv'
    )
  },

  tasksCSV: (analysis: ComprehensiveAnalysisResult, filename?: string) => {
    const content = exportTasksAsCSV(analysis)
    downloadFile(
      content,
      filename || `tasks-${analysis.analysis_id}.csv`,
      'text/csv'
    )
  },

  all: (analysis: ComprehensiveAnalysisResult) => {
    // Export all formats
    exportAnalysis.markdown(analysis)
    exportAnalysis.json(analysis)
    exportAnalysis.problemsCSV(analysis)
    exportAnalysis.featuresCSV(analysis)
    exportAnalysis.tasksCSV(analysis)
  }
}
